artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_file: D:/CDAC/Project/AI-Driven-Personal-Financial-Risk-Spending-Behavior-Analyzer/Dataset/final_financial_risk_dataset.csv
  local_data_file: artifacts/data_ingestion/final_financial_risk_dataset.csv

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/validation_status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  target_column: Risk_Label


model_trainer:
  root_dir: artifacts/model_trainer
  model_name: logistic_regression



model_evaluation:
  root_dir: artifacts/model_evaluation






