artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_file: D:/CDAC/Project/AI-Driven-Personal-Financial-Risk-Spending-Behavior-Analyzer/Dataset/final_financial_risk_dataset.csv
  local_data_file: artifacts/data_ingestion/final_financial_risk_dataset.csv

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/validation_status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  target_column: Risk_Label



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json






